### ISSUE TITLE
Run Tests Programmatically.vi behavior change?  How to know a test failed?

### ISSUE THREAD

**Issue by AndrewHeim** [JKISoftware/Caraya#130] opened 2021-03-08 19:29 UTC
Between Caraya Version 1.0 and 1.1, there looks like there was a rewrite of Run Tests Programmatically.  I believe there was a regression in that it no longer returns an error if a test fails.  It's hard to point to a single point where it changed because it looks like more of a refactor.

The impact of this is when we run unit tests with GitLab. That top level error gets turned into the Return Code when Caraya CLI returns.  (Yes, we're running Caraya CLI and started [this issue ](https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/issues/2 )there before realizing it belonged here.)

![image](https://user-images.githubusercontent.com/10777768/110370174-98685480-8008-11eb-96cc-c6a5b619cbba.png)

Note the Merge button is green even though there were failed tests (though we only see the failed tests if we catch it and click Expand).  If we roll Caraya back to 1.0, the Merge button is red as it should be if a test failed.  That is because GitLab parses the JUnit file for detailed results, but depends on the Return Code tell if overall it was a pass or failure.

Do we NEED this function to un-regress to returning an error if any test failed?  Perhaps not.  I'm fine getting results from the Test Report object returned... but that hasn't worked so far either:

![image](https://user-images.githubusercontent.com/10777768/110370338-c5b50280-8008-11eb-8c2b-e0dac580a523.png)

Running this on the latest Caraya resulted in the same no error scenario - because that array of results was empty, even though we successfully ran tests (and were able to collect the JUnit file).

So - we'd like to have an easy way of knowing directly in the CLI-called code (without parsing JUnit) whether any test failed so we can have it return the proper return code.  I don't know if that test report object isn't working, or if there's an easy way to inject an error upstream (or if you folks are strongly opinionated on which approach should be taken).

I am willing to help fix this (though I can only spare perhaps an hour a week) if need be.   But, I think I need some pointers on where to go next.

**Comment by francois-normandin** [comment] 2021-03-09 01:27
@AndrewHeim I've started looking quickly into the batch runner and I'm not too sure why the test report is empty. The test suite is destroyed after the tests are run, but I don't think it should affect the test results, being passed by value.
I'm putting together a test to reproduce this result. I hope to find time to confirm a course of action tomorrow.

**Comment by francois-normandin** [comment] 2021-03-09 22:52
Hi @AndrewHeim 
I had a quick look and reproduced your issue. There are new features that were introduced in Caraya 1.1 which make CLI calling much easier. I'll keep this issue opened because we will want to document this behavior change somewhere, but I think the new approach will be much better for CLI calling. 

You'll need to change the call in your code (and I'll patch the Caraya CLI extension project too) to use the "Run Tests.vi" call.

I made a simple test that should fail and indeed, it was marked as passed in the CLI after I upgraded to Caraya 1.1.
I then did this change: Swapping the Run Batch with the new "Run Tests" method. It effectively does all the other does, but it passes the error out. The Batch Running method was actually a call on the Tools menu app with a silent mode = true. 

![image](https://user-images.githubusercontent.com/11728548/110549518-2a06bd80-8100-11eb-80d6-799228df664f.png)

![image](https://user-images.githubusercontent.com/11728548/110548654-e52e5700-80fe-11eb-8414-d799c999fb06.png)

**Comment by AndrewHeim** [comment] 2021-03-10 00:28
Fantastic.  That worked.  Thank you and I'll follow the change when it gets to the Caraya CLI extensions.

Does this take advantage of the new CLI features, or should I watch for more great changes in the future?

**Comment by francois-normandin** [comment] 2021-03-10 00:45
You can get it here already: 
https://github.com/LabVIEW-Open-Source/Caraya-CLI-extension/releases/tag/1.1.0

As far as taking advantage of the new CLI features, I assume you are taking about LabVIEW 2018+ CLI node? If so, no... I use the G-CLI library from James McNally (@JamesMc86) which is compatible with LV2013.

I'll see if I can publish to VIPM.io soon.

**Comment by AndrewHeim** [comment] 2021-03-10 16:29
Thank you!  We can close this issue, unless you wanted to keep it open for posterity.

**Comment by francois-normandin** [comment] 2021-06-15 17:22
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6

**Closed by francois-normandin** 2021-06-15 17:22 UTC
