### ISSUE TITLE
Doubt with JUnit XML Report and Gitlab

### ISSUE THREAD

**Issue by felipefoz** [JKISoftware/Caraya#108] opened 2020-11-26 20:23 UTC
Hi, 
I've been testing the 1.1 version and I found some incompatibilities between the XML reports from 1.0.2 and 1.1.0 (Attached).

These results are happening on the CI, using the following setup for the tests.
![image](https://user-images.githubusercontent.com/63814202/100388976-db2e8f80-300a-11eb-8231-e76402509b48.png)

The CI Setup is the following. 
![image](https://user-images.githubusercontent.com/63814202/100389035-05804d00-300b-11eb-8544-58482ed80812.png)

This results in different reports within Gitlab Plataform, which I use for viewing my reports

Version 1.0.2 Gitlab Report (2 Tests - Ok)
![image](https://user-images.githubusercontent.com/63814202/100389207-863f4900-300b-11eb-80a0-440a068eb506.png)

Version 1.1.0 Gitlab Report (4 tests - redundant results)
![image](https://user-images.githubusercontent.com/63814202/100389162-585a0480-300b-11eb-841a-7d3546a50db8.png)

[XMLs.zip](https://github.com/JKISoftware/Caraya/files/5604846/XMLs.zip)

Am I missing something? What should I correct in my tests?

**Comment by francois-normandin** [comment] 2020-11-26 22:20
@felipefoz 

The change that was added and would affect your XML JUnit report is related to issue #104 .
As you can see in the screenshots, the "name" has changed... this seems to be the issue. 

The change introduced the call chain, but it seems that it affects the report's downstream filters and creates a duplicate.
Can you try this change below and see if it solves the problem? I'll create a test case anyway, but it would let me know quickly if I'm on the right track.

- Open "Caraya.lvlib:Test Report.JUnit.lvclass: Test To Report Entry.vi" and change the test suite name to use the input from the Unbundle node instead of the first caller in the Call Chain.

![image](https://user-images.githubusercontent.com/11728548/100394563-8e978400-300b-11eb-9f85-3d951a43e58f.png)

My hypothesis is that the first element of the call chain is the same as the "Name" only if you didn't give a name to your test... therefore, the unbundled name should be used.

**Comment by felipefoz** [comment] 2020-11-27 19:15
I don't know exactly what is happening to me, as I couldn't reproduce this bug on my computer.

This is happening only on my CI Server (using docker image, and caraya was mass compiled and included in the image, not using the VIPM installer).
 
But about the names, you were right, changing to obtain from the "unbundle by name" returns the name of the test correctly, and not naming the tests, includes the VI name as mentioned.

I'll keep researching why this is only happening in the CI Server, and not on my machine (really frustrated =/).

**Comment by felipefoz** [comment] 2020-11-30 13:01
Hi @francois-normandin 
I was able to reproduce the error here. Apparently the error was compiling or saving related. After resaving all the VIs and mass compiling the duplicate entries in the XML disappeared. 
As there is another issue the addresses directly the name of the test, I believe we may close this one.

**Comment by francois-normandin** [comment] 2020-11-30 13:04
@felipefoz , great to hear the problem is solved.
I agree that we can keep #109 to track the second issue mentioned.
Closing the thread.

**Closed by francois-normandin** 2020-11-30 13:04 UTC
