### ISSUE TITLE
Error 1059 with Caraya Batch testing Interface

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#63] opened 2020-01-03 09:15 UTC
I get an error 1059 using CARAYA Batch Testing Interface.
After I selected a source folder, where there where other files than *.vi files.
For instance, I had an *.xml file on the subfolders.
Maybe the code could filter on interesting files and ignore others.

**Comment by francois-normandin** [comment] 2020-01-03 12:21
Duplicate of #60

**Closed by francois-normandin** 2020-01-03 12:21 UTC
