### ISSUE TITLE
Mix between hierarchy and chronology not well supported

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#67] opened 2020-01-10 10:44 UTC
![Mix Hierarchy and chronology](https://user-images.githubusercontent.com/41787807/72146086-09c45d00-339c-11ea-9557-eae39c1cb770.png)
Following Issue #44 

As already said, I want to use several time the same VI doing  a test with one or several assertions.
In order to distinguish execution, I can define different names for Test label or assertion label as an input of the subVI.
There is now an issue where in reports, the chronology of execution does not appear, and only a hierarchy is used.
I also realize that the defined names for test does not appear (Test 1 equal 2 never appears), where for assertion names, there is no issue.

explanation on screenshot : 
- TC1 subVI let the test label by defaut (VI name), and can set a label for assertion (String control get a default value of "Assert Default Name").
- TC2 subVI let the assertion label by defaut (equal value), and can set the test label (String control get a default value of "Test Default Name").

Expected behavior : 
- TestSuite.vi
  - TC1_NamedAssertion.vi
    - Assert Default Name
  - TC1_NamedAssertion.vi
    - Assert 1 equal 2
  - Test Default Name
    - Assert Equal Value_Variant
  - Test 1 equal 2
    - Assert Equal Value_Variant
  - TC1_NamedAssertion.vi
    - Assert Default Name
  - Test Default Name
    - Assert Equal Value_Variant
  - TC1_NamedAssertion.vi
    - Assert 1 equal 2
  - Test 1 equal 2
    - Assert Equal Value_Variant

**Comment by OlivierLabo** [comment] 2020-01-10 10:47
[Mix hierarchy and chronology.zip](https://github.com/JKISoftware/Caraya/files/4045204/Mix.hierarchy.and.chronology.zip)
Attached is the example project

**Comment by francois-normandin** [comment] 2020-01-10 12:34
@OlivierLabo thanks the example project. I'll give this a try over the weekend and include something like it in the test suite should it prove am unexpected behavior.

At first glance though, the hierarchy you are looking for in the report would not be possible without having your test VIs be set for pre-allocated reentrant clones. (I could be wrong and this might be possible by changing the sorting algorithm in the year report.) If you can check the result of pre-allocated reentrancy and compare with your expectation too, that would be great.

**Comment by francois-normandin** [comment] 2020-01-12 13:41
@OlivierLabo , I did some tests with your project and I believe the test report is behaving as expected for TC1 and unexpectedly for TC2.

As I mentioned in my earlier response, I thought the behavior you are looking for would show up if your test VIs were set as pre-allocated clones, and it does. The rationale is that it creates a completely separate instance of the test for each of your test VIs, so their call chains are essentially different. As you can see in the text report and the UI screenshot: 

> 2020-01-12 08:05:28 - FAIL - TestSuite.vi - TestSuite.vi
> 2020-01-12 08:05:28 - PASS -   TC1_NamedAssertion.vi:4220001 - TC1_NamedAssertion.vi:4220001
> 2020-01-12 08:05:28 - PASS -     Assert Default Name
> 2020-01-12 08:05:28 - FAIL -   TC1_NamedAssertion.vi:4220002 - TC1_NamedAssertion.vi:4220002
> 2020-01-12 08:05:28 - FAIL -     Assert 1 equal 2
> 2020-01-12 08:05:28 - PASS -   Test Default Name - TC2_NamedTest.vi:6930001
> 2020-01-12 08:05:28 - PASS -     Assert Equal Value_Variant
> 2020-01-12 08:05:28 - FAIL -   Test 1 equal 2 - TC2_NamedTest.vi:6930002
> 2020-01-12 08:05:28 - FAIL -     Assert Equal Value_Variant
> 2020-01-12 08:05:28 - PASS -   TC1_NamedAssertion.vi:4220003 - TC1_NamedAssertion.vi:4220003
> 2020-01-12 08:05:28 - PASS -     Assert Default Name
> 2020-01-12 08:05:28 - FAIL -   TC1_NamedAssertion.vi:4220004 - TC1_NamedAssertion.vi:4220004
> 2020-01-12 08:05:28 - FAIL -     Assert 1 equal 2
> 2020-01-12 08:05:28 - PASS -   Test Default Name - TC2_NamedTest.vi:6930003
> 2020-01-12 08:05:28 - PASS -     Assert Equal Value_Variant
> 2020-01-12 08:05:28 - FAIL -   Test 1 equal 2 - TC2_NamedTest.vi:6930004
> 2020-01-12 08:05:28 - ERROR -     Assert Equal Value_Variant 

![image](https://user-images.githubusercontent.com/11728548/72219338-00113580-3513-11ea-84d4-12fed09a86f6.png)

However, if we leave them as non-reentrant, I believe the correct behavior shoud be that TC1's would all bundle together because all your TC1 test instances have the exact same call chain (you set the test label, not the test name). But TC2 instances should bundle depending on the Test Name, which they don't.

My expectation would be this result hierarchy: 

- TestSuite.vi
    - TC1_NamedAssertion.vi
        - Assert Default Name
        - Assert 1 equal 2
        - Assert Default Name
        - Assert 1 equal 2
    - Test Default Name
        - Assert Equal Value_Variant
        - Assert Equal Value_Variant
    - Assert 1 equal 2
        - Assert Equal Value_Variant
        - Assert Equal Value_Variant

**Action for dev: ** 
The second part (TC2 in your demo) does not behave like the above hierarchy, so there is a bug in ordering the results when the default Test Name has been overwritten. Currently, the ordering of the test result is being registered under the name of the first call.

**Workaround: ** 
The current workaround is to make all these test pre-allocated reentrant.

**Comment by francois-normandin** [comment] 2020-01-12 16:26
I have further details on where the problem lies. I tried seeing if the problem can be fixed in the Test Report but the root is really at test registration time.
Let's consider the following: 
First, "Define Test" registers the Call Chain + Test ID (derived from Test Label / VI Label) as a new test. At this time, the Test Manager knows of the existence of a "test". (A test being composed of 0 or more assertion results).
Second, "Assert" registers the assertion result by looking up its Call Chain and adding an Assertion Label (uniquely defined with incremental UID). At this time, the Test Manager receives an assert result, looks in the Test storage registry and adds this result by matching the Call Chain.

These two steps are not linked in any other way than through their Call Chain. It is therefore impossible with Caraya to achieve a separation based on the caller's test name because this information is not known by the subsequent assert primitive. In essence, there is no way that the assert method can be certain of the exact calling test... unless they share a unique call chain. This boils down to the re-entrancy settings again. Unless the caller of "Define Test" is a pre-allocated re-entrant clone, there is no way to keep the Defined Tests and the subsequent Assertions from knowing the "user expected" hierarchy.

Analyzing the framework, it would be necessary (to accomplish the currently discussed test report structure) to establish a direct link (class wire for example) that feeds into any assertion that is part of a defined test, so that we can pass the Test Label information. Such a construct would go against the core idea of Caraya that precludes such links in the first place.

If all tests were always carried in a serial fashion, it would be possible to establish that necessary link through a FGV instead of a class wire, but even this paradigm breaks down when tests are reconfigured to be run asynchronously (in parallel).

Considering the two different pathways below, I will propose that the only way to solve this issue in Caraya is to make those tests pre-allocated clones. (And subsequently, the current result is _a feature of the framework and not a bug_. I know it could be considered a bug if it breaks user expectation...)

![image](https://user-images.githubusercontent.com/11728548/72221924-175d1c80-352d-11ea-8506-3bf2847d7ecc.png)

@OlivierLabo, do you think this makes sense or do you see another potential pathway that I have not identified?

**Comment by OlivierLabo** [comment] 2020-01-13 09:07
Hi François,
Actually, I didn't think about reentrancy at all, but that makes sense indeed with the way Caraya is working. 
At first glance, I was thinking about a "Close Test" function going with the "Define Test" function, but as you said, in order to work as expected, and particularly in parallel branches, it would need a direct link wich is not the way Caraya as been thought of.
It's maybe not completely obvious with my way of thinking, but I totally understand why no reentrancy is needed, and the fact that it is effectively an expected behavior and not a bug.

Thank you for your in-depth analysis, and really clear explanations as always.

**Comment by francois-normandin** [comment] 2020-01-13 22:45
@OlivierLabo, great. I'll close this thread then and consider this resolved.

Indeed, a "Close Test" following a "Define Test" would be "sort of" a Setup and Tear Down that we typically see in other unit test frameworks. In Caraya, such Setups and TearDowns are meant to be executed by forcing the test to be sequential, but it is certainly not the only workflow that Caraya supports.

**Closed by francois-normandin** 2020-01-13 22:45 UTC
Labels: beta-testing 1.0, bug
