### ISSUE TITLE
Default time stamp in report when 'Define Test' is not called

### ISSUE THREAD

**Issue by laxmanraok** [JKISoftware/Caraya#83] opened 2020-04-20 16:09 UTC
When Define Test is not called (unintentional), the VI name is used as a Test Name but when this happens the time stamp/date line is returned as default value in the test report.
See the sample report below.
![image](https://user-images.githubusercontent.com/49143725/79773577-40245780-834f-11ea-853b-ccc79bbacbc1.png)

**Comment by francois-normandin** [comment] 2020-04-25 14:43
@laxmanraok Can you upload a screenshot of your test VI? 
The reason I'm asking is that I'm unsure why this line would show up in the report if you have not called "Define Test". The Define Test method is necessary to register the subsequent assertions with the framework, so its absence should indicate that the developer wishes to run the assertion method without registration. The presence of this line in the flat XML report can be interpreted as either being a bug or being the top level VI that wraps other tests (as seems to be the case with the number of tests [1472] being reported), but I'd like to confirm...
The answer to that question could influence the fix: is it a default timestamp issue or a test registration issue?

**Comment by laxmanraok** [comment] 2020-04-26 06:01
@francois-normandin 
I have tried to reproduce this but I am currently unable to but I can confirm the following.

- Here is the subVI that gave me the issue.
![image](https://user-images.githubusercontent.com/49143725/80299316-0e791980-87b1-11ea-8d9e-524e5a8398ec.png)
- I have 1471 files in total + SubVI which performs a test hence the number 1472.
- I am also sure that when I came across this problem, I missed to 'Define Test' which is why I assumed the framework used the name of the VI to automatically define the test. It's weird that I am unable to reproduce this.

**Comment by laxmanraok** [comment] 2020-04-26 06:02
By the way I don't have the label defined in the above screenshot (as I was trying to reproduce) but in the actual I have a string input ("File Names")

**Comment by francois-normandin** [comment] 2020-04-26 11:13
@laxmanraok I will continue to monitor this issue because a change has been made recently to the way test registration works; to make them unique under all circumstances (reentrancy settings, duplicate test names, etc). Therefore, the probability that a corner case is missing in the logic handling is real. 
In Caraya 0.6, I know that what you describe is the expected behavior with respect to timestamp and the default test label, but it should not be the case in 1.0.

**Comment by francois-normandin** [comment] 2020-05-03 00:13
@laxmanraok This issue turned out to be a symptom of a propagation bug up the Call Chain when a caller didn't call "Define Test" method. This is now fixed in the latest release branch commit and will be part of version 1.0.0 after final review is completed.

**Closed** 2020-05-04 21:45 UTC
Labels: beta-testing 1.0
