### ISSUE TITLE
If No Tests Found then Results Window could be more helpful (1.0 beta)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#87] opened 2020-05-04 21:57 UTC
I tried to run tests with QuickDrop Shortcut (Ctrl+Space>Ctrkl+U) and it didn't find my test because it wasn't saved to disk. The results window could probably be a little more helpful. I'm not sure what it should say, but maybe a "no tests found" message from the QD shortcut before trying to run an empty test set.

![image](https://user-images.githubusercontent.com/381432/81017467-651cce00-8e17-11ea-8f6b-6a953821d0ac.png)

FYI @francois-normandin

**Comment by francois-normandin** [comment] 2020-05-04 22:55
Yep. Added to next build. Will be released with 1.0

**Comment by PeteHorn** [comment] 2020-05-18 15:45
I'm getting the same issue but with a vi which is saved. If I call the Assert vi directly it shows the Caraya UI fine, but if I call the Assert vi inside a sub-vi I get this issue. I've disabled everything in the sub-vi except the Assert - no error is generated.

Any ideas whats going on?

![image](https://user-images.githubusercontent.com/9381579/82232820-04b58280-9927-11ea-8c24-bd35334d4772.png)

**Comment by francois-normandin** [comment] 2020-05-18 15:51
Hello @PeteHorn ,
I can confirm that this is the same root cause as the bug reported by Jim. It's been worked out and will be in the next release (whether it's a full release or another pre-release). 

There was an issue with how the assertions were linked when there was an upstream define test method (or absence of).

**Comment by francois-normandin** [comment] 2020-05-18 15:52
Now, there should not be any assertions evaluated in your second example if the DefineTest method is skipped.

**Comment by PeteHorn** [comment] 2020-05-18 15:58
Thanks for the quick response. I got it to work for now by placing the Define Test method inside the sub-vi

**Comment by francois-normandin** [comment] 2020-05-18 16:00
Yes, the DefineTest node is a prerequisite for evaluation of the assertions in your subVI

**Comment by francois-normandin** [comment] 2020-05-20 02:07
fixed in newly released 1.0.0

**Closed by francois-normandin** 2020-05-20 02:07 UTC
Labels: beta-testing 1.0
