### ISSUE TITLE
Basic test Manager.lvlcass needs save changes

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#33] opened 2019-01-21 10:11 UTC
Since last release (v0.6.0.49), I always have a popup asking for saving changes when I either load a test Suite to a Real-Time target, or when I close a project after having opened a test Suite.

I'm currently trying to integrate my tests with GitLab, so I have some scripts that launch LabVIEW, and a VI that programmatically (with VI Server) opens some projects and run VI on different targets. That VIs are using Caraya Test suites for having a Test result file that I can parse for knowing pass/fail test status.

But, because of that popup, my automatic scripts are freezed, and I can't pass my tests.

Is there a way to change something to prevent this popup? (either manually on my machine, or by a release update?)

Thanks

**Comment by OlivierLabo** [comment] 2019-01-21 10:21
Few more details:
- When launched by script, VIs are not visible, so I even can't close the popup manually.
- VIs with changes to save (recompiled) are - Caraya.lvlib : Basic Test Manager.lvlclass ; Bastic Test Manager.lvclass : about.vi ; Bastic Test Manager.lvclass : Overwrite Dialog.vi ; Bastic Test Manager.lvclass : Process.vi

**Comment by francois-normandin** [comment] 2019-01-21 13:15
Thanks Olivier. Yes, all code should be marked for "Separate compile code".

**Comment by francois-normandin** [comment] 2019-01-23 02:17
OK, just verified why I had not done that project-wide... and now I remember:
"Separate Compile Code" didn't exist in LV2009. It was [introduced](http://www.ni.com/newsletter/51258/en/) a year later in LabVIEW.

So... which strategy should we pursue to solve this? Any suggestions?

**Comment by jimkring** [comment] 2019-01-23 23:19
Could consider upgrading Caraya sources to a newer version of LabVIEW. I kind of think 2013 would be reasonable. @francois-normandin

**Comment by francois-normandin** [comment] 2019-02-18 23:46
@jimkring 
I suggest we bump the version to LV2013 when we move to Caraya 1.0.
I'd favor a refactor for the TestManager and UI to be decoupled for such a major release.
What do you think?

**Comment by jimkring** [comment] 2019-02-19 00:02
@francois-normandin Yes, I'm in favor of bumping up to to LV2013.  If we're going to refactor, I'd also like to consider doing a little bit of UX improvement, too. Specifically, I'd like to add a Search Box to make it easier to quickly find things by name.

**Comment by francois-normandin** [comment] 2019-02-19 00:03
@jimkring Let's start planning our feature requests... :-)

**Comment by francois-normandin** [comment] 2019-02-19 00:11
I'll close this issue. It is being solved by Issue #41 .
The current behavior is not a bug, but the result of using an older version of LabVIEW for the source code. Separate Compile Code will fix this problem for users on RT Target where the source code recompiles when updated.

**Closed by francois-normandin** 2019-02-19 00:11 UTC
Labels: bug

**Comment by jimkring** [comment] 2019-02-19 00:30
sounds good @francois-normandin
